linters:
  enable-all: true
  disable:
    # deprecated linters
    - golint
    - interfacer
    - scopelint
    - maligned

    # to suppress the errors in struct tags
    - tagliatelle
    # suppress type assertion warnings since we assert the same we passed
    - forcetypeassert
    # all struct has omitempty, so all fields in struct are not required
    - exhaustivestruct
    # disable gofumpt since it has conflict with wsl(white space letter) linter
    - gofumpt
    # integration tests need to done in sequential manner
    - paralleltest
    # need to allow single character variable name
    - varnamelen
    # return the error need not to wrap
    - wrapcheck
    # context needed to be stored in the struct for using refresh token 
    - containedctx

    - gochecknoglobals
    - bodyclose
    - lll 
    - noctx
  

  fast: false

issues:
  exclude:
    - type name will be used as rrset.RRsetKey.*$
    - type name will be used as token.TokenSource.*$
    - .*subtests should call t.Parallel$